---
title: Supplementary Material - Oenological parameters
author: P Solano et all
date: "`r Sys.time()`"
output:
  html_document:
    code_folding: hide
    fig_caption: yes
    force_captions: yes
    highlight: pygments
    number_sections: yes
    theme: cerulean
    toc: yes
    toc_depth: 6
    toc_float: no
    df_print: paged
  pdf_document:
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
    toc: yes
    toc_depth: 3
  word_document:
    toc: yes
    toc_depth: '3'
csl: mee.csl
subtitle: 
bibliography: bib.bib
---


<!-- [cute](https://pchiroque.github.io/basicR/Oil-summary.html) -->

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE}

require(foreign)
require(dplyr)
require(ggplot2)
require(tidyr)
library(RColorBrewer)

load("map_concentrations.rda")

library(raster)
library(sf)
library(rgl)
library(rasterVis)

# viewing
library(shiny)
library(leaflet)
library(mapview)

require(sf)
library(mapview)
library(utils)
library(webshot)
library(RColorBrewer)

  mapviewOptions(basemaps="Esri.WorldImagery")
  
  CV <- map_concent%>%
    dplyr::filter(Site=="CV",Year=="16")
  CV <- st_as_sf(CV, coords=c("Longitude","Latitude"),crs=4326)
  
mapin.CV.16.TA <- setView(mapview(CV, cex=2.5,zcol="TA",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.29383,lng=-7.72055)
  
  SL <- map_concent%>%
    dplyr::filter(Site=="SL",Year=="16")
  SL <- st_as_sf(SL, coords=c("Longitude","Latitude"),crs=4326)
  
  mapin.SL.16.TA <- setView(mapview(SL, cex=2.5,zcol="TA",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.15468,lng=-7.62829)
  
  mapin.CV.16.Brix <- setView(mapview(CV, cex=2.5,zcol="Brix",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.29383,lng=-7.72055)
  mapin.SL.16.Brix <- setView(mapview(SL, cex=2.5,zcol="Brix",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.15468,lng=-7.62829)
  
  
  mapin.CV.16.pH <- setView(mapview(CV, cex=2.5,zcol="pH",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.29383,lng=-7.72055)
  mapin.SL.16.pH <- setView(mapview(SL, cex=2.5,zcol="pH",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.15468,lng=-7.62829)
  

  mapin.CV.16.ABTS <- setView(mapview(CV, cex=2.5,zcol="ABTS",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.29383,lng=-7.72055)
  mapin.SL.16.ABTS <- setView(mapview(SL, cex=2.5,zcol="ABTS",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.15468,lng=-7.62829)
  
  
  mapin.CV.16.DPPH <- setView(mapview(CV, cex=2.5,zcol="DPPH",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.29383,lng=-7.72055)
  mapin.SL.16.DPPH <- setView(mapview(SL, cex=2.5,zcol="DPPH",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.15468,lng=-7.62829)
  
  
  mapin.CV.16.TPHEN <- setView(mapview(CV, cex=2.5,zcol="TPHEN",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.29383,lng=-7.72055)
  mapin.SL.16.TPHEN <- setView(mapview(SL, cex=2.5,zcol="TPHEN",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.15468,lng=-7.62829)
  
  
  mapin.CV.16.ODPHEN <- setView(mapview(CV, cex=2.5,zcol="ODPHEN",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.29383,lng=-7.72055)
  mapin.SL.16.ODPHEN <- setView(mapview(SL, cex=2.5,zcol="ODPHEN",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.15468,lng=-7.62829)
  
 
  mapin.CV.16.FLAV <- setView(mapview(CV, cex=2.5,zcol="FLAV",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.29383,lng=-7.72055)
  mapin.SL.16.FLAV <- setView(mapview(SL, cex=2.5,zcol="FLAV",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.15468,lng=-7.62829)
  
  
  mapin.CV.16.TANN <- setView(mapview(CV, cex=2.5,zcol="TANN",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.29383,lng=-7.72055)
  mapin.SL.16.TANN <- setView(mapview(SL, cex=2.5,zcol="TANN",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.15468,lng=-7.62829)
  
  
  mapin.CV.16.ANTH <- setView(mapview(CV, cex=2.5,zcol="ANTH",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.29383,lng=-7.72055)
  mapin.SL.16.ANTH <- setView(mapview(SL, cex=2.5,zcol="ANTH",lwd=0,col.regions=brewer.pal(9, "YlOrRd"))@map,zoom=18,lat=41.15468,lng=-7.62829)
  
  
```


# ABTS

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE, out.width="150%"}

mapin.CV.16.ABTS

mapin.SL.16.ABTS

```

# DPPH

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE, out.width="150%"}
mapin.CV.16.DPPH

mapin.SL.16.DPPH

```

# TPHEN 

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE, out.width="150%"}

mapin.CV.16.TPHEN

mapin.SL.16.TPHEN

```


# ODPHEN 

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE, out.width="150%"}

mapin.CV.16.ODPHEN

mapin.SL.16.ODPHEN

```

# FLAV 

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE, out.width="150%"}

mapin.CV.16.FLAV

mapin.SL.16.FLAV

```


# TANN 

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE, out.width="150%"}

mapin.CV.16.TANN

mapin.SL.16.TANN

```

# ANTH 

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE, out.width="150%"}

mapin.CV.16.ANTH

mapin.SL.16.ANTH

```

# Brix 

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE, out.width="150%"}

mapin.CV.16.Brix

mapin.SL.16.Brix

```

# pH 

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE, out.width="150%"}

mapin.CV.16.pH

mapin.SL.16.pH

```

# TA 

```{r echo=FALSE, message=FALSE, warning=FALSE, cache.comments=FALSE, out.width="150%"}

mapin.CV.16.TA

mapin.SL.16.TA

```

